### PR TITLE
favrskov-inprovements | Renew head of submodule.

### PR DESCRIPTION
**Pull request by sergey347**

### CODE REVIEW

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cibox03.m1.propeople.com.ua/job/PR_BUILDER/14/

**Build Log**
*last 25 lines*

 ```
[...truncated 198 lines...]
TASK: [Add general post-settings to settings.php] ***************************** 
skipping: [localhost]

TASK: [Add environment specific post-settings] ******************************** 
changed: [localhost] => (item={'status': True, 'name': '$conf["error_level"]', 'value': '2'})
changed: [localhost] => (item={'status': True, 'name': '$conf["cache"]', 'value': '0'})
changed: [localhost] => (item={'status': True, 'name': '$conf["block_cache"]', 'value': '0'})
changed: [localhost] => (item={'status': True, 'name': '$conf["preprocess_css"]', 'value': '0'})
changed: [localhost] => (item={'status': True, 'name': '$conf["preprocess_js"]', 'value': '0'})

TASK: [Copy settings back (WINDOWS)] ****************************************** 
skipping: [localhost]

TASK: [Extract archived tar ball with Fontello social icons to sites/default/files] *** 
fatal: [localhost] => input file not found at /var/www/drupal/profiles/favrskov/themes/favrskovtheme/images/icon.tar.gz or /var/www/drupal/profiles/favrskov/themes/favrskovtheme/images/icon.tar.gz

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=34   changed=21   unreachable=1    failed=0   

Build step 'Execute shell' marked build as failure
```

**Comment by sergey347** [comment]
test this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cibox03.m1.propeople.com.ua/job/PR_BUILDER/15/

**Build Log**
*last 25 lines*

 ```
[...truncated 198 lines...]
TASK: [Add general post-settings to settings.php] ***************************** 
skipping: [localhost]

TASK: [Add environment specific post-settings] ******************************** 
changed: [localhost] => (item={'status': True, 'name': '$conf["error_level"]', 'value': '2'})
changed: [localhost] => (item={'status': True, 'name': '$conf["cache"]', 'value': '0'})
changed: [localhost] => (item={'status': True, 'name': '$conf["block_cache"]', 'value': '0'})
changed: [localhost] => (item={'status': True, 'name': '$conf["preprocess_css"]', 'value': '0'})
changed: [localhost] => (item={'status': True, 'name': '$conf["preprocess_js"]', 'value': '0'})

TASK: [Copy settings back (WINDOWS)] ****************************************** 
skipping: [localhost]

TASK: [Extract archived tar ball with Fontello social icons to sites/default/files] *** 
fatal: [localhost] => input file not found at /var/www/drupal/profiles/favrskov/themes/favrskovtheme/images/icon.tar.gz or /var/www/drupal/profiles/favrskov/themes/favrskovtheme/images/icon.tar.gz

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=34   changed=21   unreachable=1    failed=0   

Build step 'Execute shell' marked build as failure
```

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cibox03.m1.propeople.com.ua/job/PR_BUILDER/16/

**Pull request merged**
