### PR TITLE
FK-362. Header minipanel updates

### PR DESCRIPTION
**Pull request by soovorov**

### CODE REVIEW

**Comment by ffw-bot-ua** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by temoor-gilmutdinov** [comment]
ok to test

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cibox03.m1.propeople.com.ua/job/PR_BUILDER/5/

**Build Log**
*last 25 lines*

 ```
[...truncated 2016 lines...]
  webform
  webform_component
  webform_emails
  webform_last_download
  webform_roles
  webform_submissions
  webform_submitted_data
  workbench_moderation_node_history
  workbench_moderation_states
  workbench_moderation_transitions
  xmlsitemap
  xmlsitemap_sitemap
 Timer                Cum (sec)  Count  Avg (msec) 
 page                 5.853      1      5852.76    
 drupal_http_request  5.38       1      5380.19

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=23   changed=16   unreachable=0    failed=1   

Build step 'Execute shell' marked build as failure
```

**Comment by temoor-gilmutdinov** [comment]
test this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cibox03.m1.propeople.com.ua/job/PR_BUILDER/6/

**Build Log**
*last 25 lines*

 ```
[...truncated 2016 lines...]
  webform
  webform_component
  webform_emails
  webform_last_download
  webform_roles
  webform_submissions
  webform_submitted_data
  workbench_moderation_node_history
  workbench_moderation_states
  workbench_moderation_transitions
  xmlsitemap
  xmlsitemap_sitemap
 Timer                Cum (sec)  Count  Avg (msec) 
 page                 5.802      1      5802.37    
 drupal_http_request  5.432      1      5431.67

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=23   changed=16   unreachable=0    failed=1   

Build step 'Execute shell' marked build as failure
```

**Comment by temoor-gilmutdinov** [comment]
test this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cibox03.m1.propeople.com.ua/job/PR_BUILDER/7/

**Build Log**
*last 25 lines*

 ```
[...truncated 2016 lines...]
  webform
  webform_component
  webform_emails
  webform_last_download
  webform_roles
  webform_submissions
  webform_submitted_data
  workbench_moderation_node_history
  workbench_moderation_states
  workbench_moderation_transitions
  xmlsitemap
  xmlsitemap_sitemap
 Timer                Cum (sec)  Count  Avg (msec) 
 page                 5.267      1      5267.24    
 drupal_http_request  4.896      1      4895.64

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=23   changed=16   unreachable=0    failed=1   

Build step 'Execute shell' marked build as failure
```

**Comment by temoor-gilmutdinov** [comment]
test this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cibox03.m1.propeople.com.ua/job/PR_BUILDER/8/

**Build Log**
*last 25 lines*

 ```
[...truncated 205 lines...]
changed: [localhost] => (item={'status': True, 'name': '$conf["preprocess_js"]', 'value': '0'})

TASK: [Copy settings back (WINDOWS)] ****************************************** 
skipping: [localhost]

TASK: [Run general drush commands] ******************************************** 
changed: [localhost] => (item={'status': True, 'name': 'sqlq', 'arguments': u'"update apachesolr_environment set url=\'http://localhost:8983/solr/default\' where env_id=\'solr\'"'})

TASK: [Run environment specific drush commands] ******************************* 
changed: [localhost] => (item={'status': True, 'name': 'sqlq', 'arguments': u'"UPDATE users SET name=\'admin\' WHERE uid=1"'})
failed: [localhost] => (item={'status': True, 'name': 'user-password', 'arguments': u'admin --password=propeople'}) => {"changed": true, "cmd": "APP_ENV=dev drush -y user-password admin --password=propeople", "delta": "0:00:00.177993", "end": "2016-09-01 14:24:00.115859", "item": {"arguments": "admin --password=propeople", "name": "user-password", "status": true}, "rc": 255, "start": "2016-09-01 14:23:59.937866", "warnings": []}
stderr: PHP Fatal error:  Class 'MemCacheDrupal' not found in /var/www/build8/includes/cache.inc on line 32
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Class 'MemCacheDrupal' not found in
/var/www/build8/includes/cache.inc, line 32

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=36   changed=23   unreachable=0    failed=1   

Build step 'Execute shell' marked build as failure
```

**Comment by temoor-gilmutdinov** [comment]
test this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cibox03.m1.propeople.com.ua/job/PR_BUILDER/9/

**Pull request merged**
