### PR TITLE
Changed construction of base url. Updated webserver role for vagrant box

### PR DESCRIPTION
**Pull request by temoor-gilmutdinov**

### CODE REVIEW

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://10.0.2.15:8080/job/PR_BUILDER/1/

**Build Log**
*last 25 lines*

 ```
[...truncated 242 lines...]
                                                
                                                
                                                



; Request: GET
/solr/favrskov/admin/luke?numTerms=0&wt=json&json.nl=map HTTP/1.0
User-Agent: Drupal (+http://drupal.org/)
Host: localhost:8080

; Caller: apachesolr_views_views_data() (line 43 of
/var/www/build1/profiles/favrskov/modules/contrib/apachesolr_views/apachesolr_views.views.inc)
WD Apache Solr Views: HTTP 404; Not Found: Not Found                 [error]
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 82 bytes) in /var/www/build1/includes/menu.inc on line 3813

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=34   changed=21   unreachable=0    failed=1   

Build step 'Execute shell' marked build as failure
```

**Comment by temoor-gilmutdinov** [comment]
test this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://10.0.2.15:8080/job/PR_BUILDER/2/

**Build Log**
*last 25 lines*

 ```
[...truncated 260 lines...]

TASK: [Install nodejs packages] *********************************************** 
changed: [localhost] => (item=jshint)

TASK: [Update ruby alternatives for using ruby 1.9.1(3) version] ************** 
skipping: [localhost]

TASK: [Install gem packages] ************************************************** 
changed: [localhost] => (item=scss-lint)

TASK: [devops/roles/cibox-security-testing | Install Security Testing] ******** 
failed: [localhost] => {"changed": true, "cmd": "rsync -avz devops/modules/ sites/all/modules/contrib/", "delta": "0:00:00.111311", "end": "2016-09-01 12:55:40.245374", "rc": 11, "start": "2016-09-01 12:55:40.134063", "warnings": ["Consider using synchronize module rather than running rsync"]}
stderr: rsync: mkdir "/var/www/build2/sites/all/modules/contrib" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.0]
stdout: sending incremental file list

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/sniffers.retry

localhost                  : ok=11   changed=8    unreachable=0    failed=1   

Build step 'Execute shell' marked build as failure
```

**Comment by temoor-gilmutdinov** [comment]
test this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cibox03.m1.propeople.com.ua/job/PR_BUILDER/3/

**Pull request merged**
